site_name: SORMAS Stats
repo_name: 'hzi-braunschweig/SORMAS-Stats'
repo_url: 'https://github.com/hzi-braunschweig/SORMAS-Stats'

theme:
  name: material
  features:
  - tabs
extra:
  version: 0.10
  palette:
    primary: 'green'
  social:
  - icon: 'fontawesome/brands/github-alt'
    link: 'https://github.com/hzi-braunschweig/SORMAS-Stats'
plugins:
- search:
    separator: '[\s]+'

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences

nav:
- Sormas Stats:
  - Sormas Stats: 'index.md'
- Jupyter:
  - 'jupyter.md'
- Python:
  - 'python.md'
- R:
  - R: 'r.md'
- Generate Data:
  - Generate Data: 'data-gen.md'
- Offical Website: "https://sormas.org"